### ISSUE TITLE
小小输入法→系统栏图标→右键菜单→输出方式 丢失 crash

### ISSUE THREAD

**Issue by longwu9t** [dgod/yong#12]
操作系统是win10 ltsc 2019
输入法版本已网络升级到最新版
yong.exe 32bit 管理员权限运行
输出方式采用默认
class.txt在自带的基础上添加了Edit这一项以解决一个小程序的无法上屏问题
以下故障可以重复出现
经常性在chrome输入框内出现类似剪贴板输出方式的卡顿
而后就会出现yong输入法系统栏图标右键菜单项中的输出方式一项消失
还会伴有不规律的crash
crash.txt内容如下：

Code ACCESS_VIOLATION
Addr 00000000 unknown2 0000:00000000
Op read
Data 00000000

Call stack:
Address   Frame     Logical addr  Module
00000000  0065F954  0000:00000000 unknown2
75B669DC  0065FA38  0001:000359DC C:\Windows\System32\USER32.dll
75B65B1B  0065FAAC  0001:00034B1B C:\Windows\System32\USER32.dll
75B658F0  0065FAB8  0001:000348F0 C:\Windows\System32\USER32.dll

**Comment by dgod** [comment]
无法重现
