### ISSUE TITLE
【Suggested & Help】How to participate in contributing

### ISSUE THREAD

**Issue by maojunxyz** [dgod/yong#14]
How can I participate in the development of YONG input method, I am java programmer. But interested in c language and would like to be involved in maintaining this project. This is a good project to improve my work efficiency. I suggest the author can open a sponsorship, I would love to buy a cup of coffee for this project, and I believe others who are helped by this project will do the same. I hope this project stays updated and open source.

Likewise, I will recommend YONG input method to my friends and colleagues, and write some blogs about YONG.

**Comment by dgod** [comment]
yong project is a person only project, and used in china only. If you have have interest in IME, fcitx is a better option.
