### ISSUE TITLE
建议：开关Yong的快捷键可接受其他程序发送

### ISSUE THREAD

**Issue by dummyvoid** [dgod/yong#16]
当前版本下，开关Yong的快捷键一旦设置后，用其他程序(例如按键精灵之类)发送相同的快捷键是无法开关Yong的，不利与其他程序的协同使用。

**Comment by dgod** [comment]
和其他程序通信是通过yong-vim程序进行的，详见https://yong.dgod.net/read.php?tid=2155&fid=7。

**Comment by dummyvoid** [comment]
谢谢，看了之后还是没有我需要的...
请问：
1. 用yong-vim开关Yong的命令怎么写？
2. 用yong-vim切换输入法的命令怎么写？

**Comment by dgod** [comment]
设置中英文，应该能满足你开关输入法的要求吧。
有切换输入法的实际使用需求吗？

其他程序发过来的按键处理不了，是因为没有携带scanCode(扫描码）信息。如果默认是使用内置的模块，则是可以处理按键的。

**Comment by dummyvoid** [comment]
开关输入法主要是为了显示与隐藏输入法窗口。
切换输入法是因为在某些程序中使用时，有需要在按下该程序自带的快捷键的同时也连带切换输入法。
可能我的需求比较小众，但如果有一些方法的话对我会方便许多，谢谢。

**Comment by dgod** [comment]
更新一下程序吧，增强了一下yong-vim功能，具体见帮助
