### ISSUE TITLE
Manjaro系统下kde桌面下小小输入法无法输出中文

### ISSUE THREAD

**Issue by wedo99** [dgod/yong#6]
大神您好：
我已经编译成功了。
然后安装的时候使用的是编译好的输入法，
编译好的qt模块也放 系统这个路径下了：
/usr/lib64/qt5/plugins/platforminputcontexts/libyongplatforminputcontextplugin.so

.profile配置文件试过好多遍，配置如下：
`export GTK_IM_MODULE=yong`
`export QT_IM_MODULE=yong`
`export XMODIFIERS=@im=yong`
`
source过，系统也重启了好多遍

输入法窗口的工具栏下也点击过软件更新了

只是问题还是没有解决，还是和没有编译的情况一样，任务栏里红色的小图标能出来，右键进行设置也可以，就是中文还是出不来。

现在情况好点了，只有Manjaro自带的火狐浏览器可以输入中文，其他的都不行。

我的环境是：在联想笔记本上安装的Manjaro-kde-18.0，64位系统
笔记本是4年前买的配置还可以i7+12G内存
问题应该是小小输入法与kde桌面冲突，与另外一位使用Manjaro但是桌面是xfce桌面引擎的不用编译都没有问题。

希望大神您能否指点一二

**Comment by dgod** [comment]
你可以在kde的terminal里看一下环境变量有没有加载成功
另外小小输入法的qt模块有特别要求，系统的QT库必须编译进GLIB支持，否则不能正常工作。你可以查看一下程序有没有成功加载qt模块

**Comment by wedo99** [comment]
放弃了，改换Manjaro-gnome了，在好几个软件里都试了，如浏览器，文本编辑器，终端，其他软件，发现除了浏览器其他都不行。就算解决了说不定也隐藏着不易发现的问题，我是做Java和Python的，查看QT有没有编译进GLIB和成功加载qt模块，之前光编译非常都十分不易，还不如换桌面引擎呢

**Comment by dgod** [comment]
考虑到qt的兼容性太差，出了问题推荐自己编译解决
