### ISSUE TITLE
Deepin 15.11版本使用中的一些问题

### ISSUE THREAD

**Issue by tianxiayu007** [dgod/yong#8]
今天花了一些时间再次尝试使用小小，比较沮丧的是仍然遇到了不少问题~~
1.起初按常规步骤安装:
```bash
sudo yong-tool.sh --install64
yong-tool.sh --select
```
手动启动yong提示“yong start fail, may XIM daemon named "fcitx" there”，这个问题网上搜了半天，因为大部分页面并没有提到yong跟fcitx冲突啊？！（只是说yong不依赖其他输入法框架，而且yong可以在ibus下使用）
2.第一步的问题通过卸载fcitx，卸载搜狗等乱七八糟的包后解决，这时候yong可以启动了，工具栏右下角也显示图标，但是不管重启还是注销都无法打中文
3.第二步的问题实在无法解决，准备放弃的时候，重新下载了压缩包安装后又可以了，玄学啊？？！！
从安装脚本看，怀疑是成功安装的这次是因为系统有im-config，说明没有im-config 的情况下脚本生成的配置是无效的
```bash
 function debian_install()
{
	if [ -e /usr/share/im-config ] ; then
		debian_install2
		return
	fi
	
	CFG=/etc/X11/xinit/xinput.d/yong
	
	cat >$CFG <<EOF
XMODIFIERS="@im=yong"
XIM="yong"
XIM_PROGRAM="/usr/bin/yong"
XIM_ARGS=""
if [ -e $GTK_IM_DETECT/*/immodules/im-yong.so ] ; then
	GTK_IM_MODULE="yong"
else
	GTK_IM_MODULE="xim"
fi
QT_IM_MODULE="xim"
SHORT_DESC="yong"
PREFERENCE_PROGRAM="/usr/bin/yong-config"
EOF

	update-alternatives \
	       	--install /etc/X11/xinit/xinput.d/zh_CN xinput-zh_CN \
       		/etc/X11/xinit/xinput.d/yong 20
}
```
4.然后继续体验，发现在部分应用如文件管理器等无法输入中文，网上的教程是复制qt插件到指定
目录，我把168网盘上qt的插件全部试了一遍是没有效果的~~
```bash
#!/bin/bash
mkdir -p /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts
cp -rf ./libyongplatforminputcontextplugin.so /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts
chmod -R 777 /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts
chmod +x /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libyongplatforminputcontextplugin.so
echo "QT5 plugin success install"
```
5.最让我崩溃的问题是，yong在不同应用间无法保持输入法状态，具体如下：
我同时打开了A，B2个应用，A应用下我切换到中文，然后我把光标切换到B应用后，B应用的输入法状态是英文或者未启用yong，也就是yong没有在全局范围内维持自身的状态，这用着就难受了！！

以上的4，5点是我暂时无法解决的问题，不知是否有解决方法？？

**Comment by fygul** [comment]
5.的現象應該是正常的吧。每個應用都有它自己獨自的輸入法狀態，不是嗎？

**Comment by fygul** [comment]
關於4.
你的QT5的版號？

不知[這篇](http://fygul.blogspot.com/2018/08/yong-qt5-plugin.html)是否對你有用？

**Comment by tianxiayu007** [comment]
> 5.的現象應該是正常的吧。每個應用都有它自己獨自的輸入法狀態，不是嗎？

目前使用过的所有输入法都是全局一致状态的, 否则疲于在不同应用间切换状态,真的痛苦😢

**Comment by tianxiayu007** [comment]
> 關於4.
> 你的QT5的版號？
> 
> 不知[這篇](http://fygul.blogspot.com/2018/08/yong-qt5-plugin.html)是否對你有用？

ok,明白了...Deepin 15.11的qt版本为5.7.1,网盘上有5.7.0的,但好像都无效
`dpkg -l | grep qt5`

**Comment by dispensable** [comment]
> > 關於4.
> > 你的QT5的版號？
> > 不知[這篇](http://fygul.blogspot.com/2018/08/yong-qt5-plugin.html)是否對你有用？
> 
> ok,明白了...Deepin 15.11的qt版本为5.7.1,网盘上有5.7.0的,但好像都无效
> `dpkg -l | grep qt5`

http://yong.dgod.net/read.php?tid=2247
qt的直接自己编一下,很简单。另外共享状态其实切的频率更高

**Comment by dgod** [comment]
时间过去，根据当前各个发行版的现状，现在暂时linux只推荐在ibus下使用，如果ibus可用的话
